# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Optional
from typing_extensions import Literal

from ..._models import BaseModel

__all__ = ["PaymentMethodDetailsCardPresentReceipt"]


class PaymentMethodDetailsCardPresentReceipt(BaseModel):
    account_type: Optional[Literal["checking", "credit", "prepaid", "unknown"]] = None
    """The type of account being debited or credited"""

    application_cryptogram: Optional[str] = None
    """
    The Application Cryptogram, a unique value generated by the card to authenticate
    the transaction with issuers.
    """

    application_preferred_name: Optional[str] = None
    """
    The Application Identifier (AID) on the card used to determine which networks
    are eligible to process the transaction. Referenced from EMV tag 9F12, data
    encoded on the card's chip.
    """

    authorization_code: Optional[str] = None
    """Identifier for this transaction."""

    authorization_response_code: Optional[str] = None
    """EMV tag 8A. A code returned by the card issuer."""

    cardholder_verification_method: Optional[str] = None
    """Describes the method used by the cardholder to verify ownership of the card.

    One of the following: `approval`, `failure`, `none`, `offline_pin`,
    `offline_pin_and_signature`, `online_pin`, or `signature`.
    """

    dedicated_file_name: Optional[str] = None
    """
    Similar to the application_preferred_name, identifying the applications (AIDs)
    available on the card. Referenced from EMV tag 84.
    """

    terminal_verification_results: Optional[str] = None
    """
    A 5-byte string that records the checks and validations that occur between the
    card and the terminal. These checks determine how the terminal processes the
    transaction and what risk tolerance is acceptable. Referenced from EMV Tag 95.
    """

    transaction_status_information: Optional[str] = None
    """An indication of which steps were completed during the card read process.

    Referenced from EMV Tag 9B.
    """
