# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Dict, Union, Iterable
from typing_extensions import Literal, Required, TypedDict

from .._types import SequenceNotStr

__all__ = [
    "ProductCreateParams",
    "DefaultPriceData",
    "DefaultPriceDataCurrencyOptions",
    "DefaultPriceDataCurrencyOptionsCustomUnitAmount",
    "DefaultPriceDataCurrencyOptionsTier",
    "DefaultPriceDataCustomUnitAmount",
    "DefaultPriceDataRecurring",
    "MarketingFeature",
    "PackageDimensions",
]


class ProductCreateParams(TypedDict, total=False):
    name: Required[str]
    """The product's name, meant to be displayable to the customer."""

    id: str
    """An identifier will be randomly generated by Stripe.

    You can optionally override this ID, but the ID must be unique across all
    products in your Stripe account.
    """

    active: bool
    """Whether the product is currently available for purchase. Defaults to `true`."""

    default_price_data: DefaultPriceData
    """Data used to generate a new [Price](https://docs.stripe.com/api/prices) object.

    This Price will be set as the default price for this product.
    """

    description: str
    """The product's description, meant to be displayable to the customer.

    Use this field to optionally store a long form explanation of the product being
    sold for your own rendering purposes.
    """

    expand: SequenceNotStr[str]
    """Specifies which fields in the response should be expanded."""

    images: SequenceNotStr[str]
    """
    A list of up to 8 URLs of images for this product, meant to be displayable to
    the customer.
    """

    marketing_features: Iterable[MarketingFeature]
    """A list of up to 15 marketing features for this product.

    These are displayed in
    [pricing tables](https://docs.stripe.com/payments/checkout/pricing-table).
    """

    metadata: Dict[str, str]
    """
    Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can
    attach to an object. This can be useful for storing additional information about
    the object in a structured format. Individual keys can be unset by posting an
    empty value to them. All keys can be unset by posting an empty value to
    `metadata`.
    """

    package_dimensions: PackageDimensions
    """The dimensions of this product for shipping purposes."""

    shippable: bool
    """Whether this product is shipped (i.e., physical goods)."""

    statement_descriptor: str
    """
    An arbitrary string to be displayed on your customer's credit card or bank
    statement. While most banks display this information consistently, some may
    display it incorrectly or not at all.

    This may be up to 22 characters. The statement description may not include `<`,
    `>`, `\\``, `"`, `'` characters, and will appear on your customer's statement in
    capital letters. Non-ASCII characters are automatically stripped. It must
    contain at least one letter. Only used for subscription payments.
    """

    tax_code: str
    """A [tax code](https://docs.stripe.com/tax/tax-categories) ID."""

    unit_label: str
    """A label that represents units of this product.

    When set, this will be included in customers' receipts, invoices, Checkout, and
    the customer portal.
    """

    url: str
    """A URL of a publicly-accessible webpage for this product."""


class DefaultPriceDataCurrencyOptionsCustomUnitAmount(TypedDict, total=False):
    enabled: Required[bool]

    maximum: int

    minimum: int

    preset: int


class DefaultPriceDataCurrencyOptionsTier(TypedDict, total=False):
    up_to: Required[Union[Literal["inf"], int]]

    flat_amount: int

    flat_amount_decimal: str

    unit_amount: int

    unit_amount_decimal: str


class DefaultPriceDataCurrencyOptions(TypedDict, total=False):
    custom_unit_amount: DefaultPriceDataCurrencyOptionsCustomUnitAmount

    tax_behavior: Literal["exclusive", "inclusive", "unspecified"]

    tiers: Iterable[DefaultPriceDataCurrencyOptionsTier]

    unit_amount: int

    unit_amount_decimal: str


class DefaultPriceDataCustomUnitAmount(TypedDict, total=False):
    enabled: Required[bool]

    maximum: int

    minimum: int

    preset: int


class DefaultPriceDataRecurring(TypedDict, total=False):
    interval: Required[Literal["day", "month", "week", "year"]]

    interval_count: int


class DefaultPriceData(TypedDict, total=False):
    """Data used to generate a new [Price](https://docs.stripe.com/api/prices) object.

    This Price will be set as the default price for this product.
    """

    currency: Required[str]

    currency_options: Dict[str, DefaultPriceDataCurrencyOptions]

    custom_unit_amount: DefaultPriceDataCustomUnitAmount

    metadata: Dict[str, str]

    recurring: DefaultPriceDataRecurring

    tax_behavior: Literal["exclusive", "inclusive", "unspecified"]

    unit_amount: int

    unit_amount_decimal: str


class MarketingFeature(TypedDict, total=False):
    name: Required[str]


class PackageDimensions(TypedDict, total=False):
    """The dimensions of this product for shipping purposes."""

    height: Required[float]

    length: Required[float]

    weight: Required[float]

    width: Required[float]
