# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import TYPE_CHECKING, Union, Optional
from typing_extensions import TypeAlias, TypeAliasType

from .._compat import PYDANTIC_V1
from .._models import BaseModel
from .shared.payment_method_details_card_present_offline import PaymentMethodDetailsCardPresentOffline

__all__ = ["SetupAttemptPaymentMethodDetailsCardPresent", "GeneratedCard"]

if TYPE_CHECKING or not PYDANTIC_V1:
    GeneratedCard = TypeAliasType("GeneratedCard", Union[str, "PaymentMethod", None])
else:
    GeneratedCard: TypeAlias = Union[str, "PaymentMethod", None]


class SetupAttemptPaymentMethodDetailsCardPresent(BaseModel):
    generated_card: Optional[GeneratedCard] = None
    """The ID of the Card PaymentMethod which was generated by this SetupAttempt."""

    offline: Optional[PaymentMethodDetailsCardPresentOffline] = None


from .payment_method import PaymentMethod
