# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

import builtins
from typing import TYPE_CHECKING, List, Union, Optional
from typing_extensions import Literal, TypeAlias, TypeAliasType

from .._compat import PYDANTIC_V1
from .._models import BaseModel

__all__ = [
    "Mandate",
    "CustomerAcceptance",
    "CustomerAcceptanceOnline",
    "PaymentMethod",
    "PaymentMethodDetails",
    "PaymentMethodDetailsAcssDebit",
    "PaymentMethodDetailsAuBecsDebit",
    "PaymentMethodDetailsBacsDebit",
    "PaymentMethodDetailsPaypal",
    "PaymentMethodDetailsPayto",
    "PaymentMethodDetailsSepaDebit",
    "PaymentMethodDetailsUsBankAccount",
    "SingleUse",
]


class CustomerAcceptanceOnline(BaseModel):
    ip_address: Optional[str] = None
    """The customer accepts the mandate from this IP address."""

    user_agent: Optional[str] = None
    """The customer accepts the mandate using the user agent of the browser."""


class CustomerAcceptance(BaseModel):
    type: Literal["offline", "online"]
    """
    The mandate includes the type of customer acceptance information, such as:
    `online` or `offline`.
    """

    accepted_at: Optional[int] = None
    """The time that the customer accepts the mandate."""

    offline: Optional[object] = None

    online: Optional[CustomerAcceptanceOnline] = None


if TYPE_CHECKING or not PYDANTIC_V1:
    PaymentMethod = TypeAliasType("PaymentMethod", Union[str, "payment_method.PaymentMethod"])
else:
    PaymentMethod: TypeAlias = Union[str, "payment_method.PaymentMethod"]


class PaymentMethodDetailsAcssDebit(BaseModel):
    payment_schedule: Literal["combined", "interval", "sporadic"]
    """Payment schedule for the mandate."""

    transaction_type: Literal["business", "personal"]
    """Transaction type of the mandate."""

    default_for: Optional[List[Literal["invoice", "subscription"]]] = None
    """List of Stripe products where this mandate can be selected automatically."""

    interval_description: Optional[str] = None
    """Description of the interval.

    Only required if the 'payment_schedule' parameter is 'interval' or 'combined'.
    """


class PaymentMethodDetailsAuBecsDebit(BaseModel):
    url: str
    """The URL of the mandate.

    This URL generally contains sensitive information about the customer and should
    be shared with them exclusively.
    """


class PaymentMethodDetailsBacsDebit(BaseModel):
    network_status: Literal["accepted", "pending", "refused", "revoked"]
    """The status of the mandate on the Bacs network.

    Can be one of `pending`, `revoked`, `refused`, or `accepted`.
    """

    reference: str
    """The unique reference identifying the mandate on the Bacs network."""

    url: str
    """The URL that will contain the mandate that the customer has signed."""

    revocation_reason: Optional[
        Literal[
            "account_closed",
            "bank_account_restricted",
            "bank_ownership_changed",
            "could_not_process",
            "debit_not_authorized",
        ]
    ] = None
    """
    When the mandate is revoked on the Bacs network this field displays the reason
    for the revocation.
    """


class PaymentMethodDetailsPaypal(BaseModel):
    billing_agreement_id: Optional[str] = None
    """The PayPal Billing Agreement ID (BAID).

    This is an ID generated by PayPal which represents the mandate between the
    merchant and the customer.
    """

    payer_id: Optional[str] = None
    """PayPal account PayerID.

    This identifier uniquely identifies the PayPal customer.
    """


class PaymentMethodDetailsPayto(BaseModel):
    amount_type: Literal["fixed", "maximum"]
    """The type of amount that will be collected.

    The amount charged must be exact or up to the value of `amount` param for
    `fixed` or `maximum` type respectively. Defaults to `maximum`.
    """

    payment_schedule: Literal[
        "adhoc", "annual", "daily", "fortnightly", "monthly", "quarterly", "semi_annual", "weekly"
    ]
    """The periodicity at which payments will be collected. Defaults to `adhoc`."""

    amount: Optional[int] = None
    """Amount that will be collected. It is required when `amount_type` is `fixed`."""

    end_date: Optional[str] = None
    """Date, in YYYY-MM-DD format, after which payments will not be collected.

    Defaults to no end date.
    """

    payments_per_period: Optional[int] = None
    """The number of payments that will be made during a payment period.

    Defaults to 1 except for when `payment_schedule` is `adhoc`. In that case, it
    defaults to no limit.
    """

    purpose: Optional[
        Literal[
            "dependant_support",
            "government",
            "loan",
            "mortgage",
            "other",
            "pension",
            "personal",
            "retail",
            "salary",
            "tax",
            "utility",
        ]
    ] = None
    """The purpose for which payments are made.

    Has a default value based on your merchant category code.
    """

    start_date: Optional[str] = None
    """Date, in YYYY-MM-DD format, from which payments will be collected.

    Defaults to confirmation time.
    """


class PaymentMethodDetailsSepaDebit(BaseModel):
    reference: str
    """The unique reference of the mandate."""

    url: str
    """The URL of the mandate.

    This URL generally contains sensitive information about the customer and should
    be shared with them exclusively.
    """


class PaymentMethodDetailsUsBankAccount(BaseModel):
    collection_method: Optional[Literal["paper"]] = None
    """Mandate collection method"""


class PaymentMethodDetails(BaseModel):
    type: str
    """This mandate corresponds with a specific payment method type.

    The `payment_method_details` includes an additional hash with the same name and
    contains mandate information that's specific to that payment method.
    """

    acss_debit: Optional[PaymentMethodDetailsAcssDebit] = None

    amazon_pay: Optional[object] = None

    au_becs_debit: Optional[PaymentMethodDetailsAuBecsDebit] = None

    bacs_debit: Optional[PaymentMethodDetailsBacsDebit] = None

    card: Optional[object] = None

    cashapp: Optional[object] = None

    kakao_pay: Optional[object] = None

    klarna: Optional[object] = None

    kr_card: Optional[object] = None

    link: Optional[object] = None

    naver_pay: Optional[object] = None

    nz_bank_account: Optional[object] = None

    paypal: Optional[PaymentMethodDetailsPaypal] = None

    payto: Optional[PaymentMethodDetailsPayto] = None

    revolut_pay: Optional[object] = None

    sepa_debit: Optional[PaymentMethodDetailsSepaDebit] = None

    us_bank_account: Optional[PaymentMethodDetailsUsBankAccount] = None


class SingleUse(BaseModel):
    amount: int
    """The amount of the payment on a single use mandate."""

    currency: str
    """The currency of the payment on a single use mandate."""


class Mandate(BaseModel):
    """
    A Mandate is a record of the permission that your customer gives you to debit their payment method.
    """

    id: str
    """Unique identifier for the object."""

    customer_acceptance: CustomerAcceptance

    livemode: bool
    """
    Has the value `true` if the object exists in live mode or the value `false` if
    the object exists in test mode.
    """

    object: Literal["mandate"]
    """String representing the object's type.

    Objects of the same type share the same value.
    """

    payment_method: PaymentMethod
    """ID of the payment method associated with this mandate."""

    payment_method_details: PaymentMethodDetails

    status: Literal["active", "inactive", "pending"]
    """
    The mandate status indicates whether or not you can use it to initiate a
    payment.
    """

    type: Literal["multi_use", "single_use"]
    """The type of the mandate."""

    multi_use: Optional[builtins.object] = None

    on_behalf_of: Optional[str] = None
    """The account (if any) that the mandate is intended for."""

    single_use: Optional[SingleUse] = None


from . import payment_method
