# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import TYPE_CHECKING, Union, Optional
from typing_extensions import Literal, TypeAlias, TypeAliasType

from .._compat import PYDANTIC_V1
from .._models import BaseModel

__all__ = ["PaymentMethodDetailsIdealSetupAttempt", "GeneratedSepaDebit", "GeneratedSepaDebitMandate"]

if TYPE_CHECKING or not PYDANTIC_V1:
    GeneratedSepaDebit = TypeAliasType("GeneratedSepaDebit", Union[str, "PaymentMethod", None])
else:
    GeneratedSepaDebit: TypeAlias = Union[str, "PaymentMethod", None]

if TYPE_CHECKING or not PYDANTIC_V1:
    GeneratedSepaDebitMandate = TypeAliasType("GeneratedSepaDebitMandate", Union[str, "Mandate", None])
else:
    GeneratedSepaDebitMandate: TypeAlias = Union[str, "Mandate", None]


class PaymentMethodDetailsIdealSetupAttempt(BaseModel):
    bank: Optional[
        Literal[
            "abn_amro",
            "adyen",
            "asn_bank",
            "bunq",
            "buut",
            "finom",
            "handelsbanken",
            "ing",
            "knab",
            "mollie",
            "moneyou",
            "n26",
            "nn",
            "rabobank",
            "regiobank",
            "revolut",
            "sns_bank",
            "triodos_bank",
            "van_lanschot",
            "yoursafe",
        ]
    ] = None
    """The customer's bank.

    Can be one of `abn_amro`, `adyen`, `asn_bank`, `bunq`, `buut`, `finom`,
    `handelsbanken`, `ing`, `knab`, `mollie`, `moneyou`, `n26`, `nn`, `rabobank`,
    `regiobank`, `revolut`, `sns_bank`, `triodos_bank`, `van_lanschot`, or
    `yoursafe`.
    """

    bic: Optional[
        Literal[
            "ABNANL2A",
            "ADYBNL2A",
            "ASNBNL21",
            "BITSNL2A",
            "BUNQNL2A",
            "BUUTNL2A",
            "FNOMNL22",
            "FVLBNL22",
            "HANDNL2A",
            "INGBNL2A",
            "KNABNL2H",
            "MLLENL2A",
            "MOYONL21",
            "NNBANL2G",
            "NTSBDEB1",
            "RABONL2U",
            "RBRBNL21",
            "REVOIE23",
            "REVOLT21",
            "SNSBNL2A",
            "TRIONL2U",
        ]
    ] = None
    """The Bank Identifier Code of the customer's bank."""

    generated_sepa_debit: Optional[GeneratedSepaDebit] = None
    """
    The ID of the SEPA Direct Debit PaymentMethod which was generated by this
    SetupAttempt.
    """

    generated_sepa_debit_mandate: Optional[GeneratedSepaDebitMandate] = None
    """
    The mandate for the SEPA Direct Debit PaymentMethod which was generated by this
    SetupAttempt.
    """

    iban_last4: Optional[str] = None
    """Last four characters of the IBAN."""

    verified_name: Optional[str] = None
    """Owner's verified full name.

    Values are verified or provided by iDEAL directly (if supported) at the time of
    authorization or settlement. They cannot be set or mutated.
    """


from .mandate import Mandate
from .payment_method import PaymentMethod
