# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import TYPE_CHECKING, Union, Optional
from typing_extensions import Literal, TypeAlias, TypeAliasType

from .._compat import PYDANTIC_V1
from .._models import BaseModel

__all__ = ["PaymentMethodDetailsBancontactDispute", "GeneratedSepaDebit", "GeneratedSepaDebitMandate"]

if TYPE_CHECKING or not PYDANTIC_V1:
    GeneratedSepaDebit = TypeAliasType("GeneratedSepaDebit", Union[str, "PaymentMethod", None])
else:
    GeneratedSepaDebit: TypeAlias = Union[str, "PaymentMethod", None]

if TYPE_CHECKING or not PYDANTIC_V1:
    GeneratedSepaDebitMandate = TypeAliasType("GeneratedSepaDebitMandate", Union[str, "Mandate", None])
else:
    GeneratedSepaDebitMandate: TypeAlias = Union[str, "Mandate", None]


class PaymentMethodDetailsBancontactDispute(BaseModel):
    bank_code: Optional[str] = None
    """Bank code of bank associated with the bank account."""

    bank_name: Optional[str] = None
    """Name of the bank associated with the bank account."""

    bic: Optional[str] = None
    """Bank Identifier Code of the bank associated with the bank account."""

    generated_sepa_debit: Optional[GeneratedSepaDebit] = None
    """
    The ID of the SEPA Direct Debit PaymentMethod which was generated by this
    Charge.
    """

    generated_sepa_debit_mandate: Optional[GeneratedSepaDebitMandate] = None
    """
    The mandate for the SEPA Direct Debit PaymentMethod which was generated by this
    Charge.
    """

    iban_last4: Optional[str] = None
    """Last four characters of the IBAN."""

    preferred_language: Optional[Literal["de", "en", "fr", "nl"]] = None
    """
    Preferred language of the Bancontact authorization page that the customer is
    redirected to. Can be one of `en`, `de`, `fr`, or `nl`
    """

    verified_name: Optional[str] = None
    """Owner's verified full name.

    Values are verified or provided by Bancontact directly (if supported) at the
    time of authorization or settlement. They cannot be set or mutated.
    """


from .mandate import Mandate
from .payment_method import PaymentMethod
