# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import TYPE_CHECKING, List, Union, Optional
from typing_extensions import TypeAlias, TypeAliasType

from .._compat import PYDANTIC_V1
from .._models import BaseModel
from .shared.deleted_tax_id import DeletedTaxID

__all__ = ["SubscriptionInvoiceSettings", "AccountTaxID"]

if TYPE_CHECKING or not PYDANTIC_V1:
    AccountTaxID = TypeAliasType("AccountTaxID", Union[str, "TaxID", DeletedTaxID])
else:
    AccountTaxID: TypeAlias = Union[str, "TaxID", DeletedTaxID]


class SubscriptionInvoiceSettings(BaseModel):
    issuer: "ConnectAccountReference"

    account_tax_ids: Optional[List[AccountTaxID]] = None
    """The account tax IDs associated with the subscription.

    Will be set on invoices generated by the subscription.
    """


from .tax_id import TaxID
from .connect_account_reference import ConnectAccountReference
